export enum City {
    'Agadir' = 'Agadir',
    'AlHoceima' = 'AlHoceima',
    'Asilah' = 'Asilah',
    'Casablanca'= 'Casablanca',
    'Chefchaouen' = 'Chefchaouen',
    'ElJadida' = 'ElJadida',
    'Errachidia' = 'Errachidia',
    'Essaouira' = 'Essaouira',
    'Fes' = 'Fes',
    'Ifrane' = 'Ifrane',
    'Marrakech' = 'Marrakech',
    'Meknes' = 'Meknes',
    'Nador' = 'Nador',
    'Ouarzazate' = 'Ouarzazate',
    'Oujda' = 'Oujda',
    'Rabat' = 'Rabat',
    'Safi' = 'Safi',
    'Tanger' = 'Tanger',
    'Taroudant' = 'Taroudant',
    'Tetouan' = 'Tetouan',
    'Zagora' = 'Zagora'
}
